# spring config
spring:
  application:
    name: seed
  profiles:
    active: dev, common, plus, tk

logging:
  level:
    cn.zm: debug

# global config
config:
  netty:
    websocket:
      path: /ws
      port: 9020