spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seedDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC  #?characterEncoding=utf8
    #serverTimezone: UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
# thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
server:
  port: 8080
  servlet:
    context-path: /

# 设定访问Api doc的路由这个 path 就是 json 的访问 request mapping. 可以自定义，防止与自身代码冲突。
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs