# spring config
spring:
  application:
    name: seed
  profiles:
    active: dev
# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml   #XML文件路径
  type-aliases-package: cn.zm.modules
  generate:
    package: cn.zm
