#db
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml   #XML文件路径
  type-aliases-package: cn.zm.mybatis.plus
  generate:
    module: mybatis-plus
    package: cn.zm.mybatis.plus